import Link from "next/link";
import { ArrowRight, CalendarClock, ChefHat, CircleGauge, PackageOpen, Plus, ShoppingBasket, Sparkles } from "lucide-react";
import { auth } from "@/auth";
import { getPrisma } from "@/server/prisma";
import { getCompatibleRecipes } from "@/features/recipes/service";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/page-header";
import { formatDate } from "@/lib/utils";

export const dynamic = "force-dynamic";
export default async function DashboardPage() {
  const session = await auth(); const userId = session!.user.id; const db = getPrisma(); const now = new Date(); const soon = new Date(now.getTime() + 7 * 86400000);
  const [inventoryCount, expiring, lowStock, leftovers, recent, recipes, shoppingCount] = await Promise.all([
    db.inventoryItem.count({ where: { userId, normalizedQuantity: { gt: 0 } } }),
    db.inventoryItem.findMany({ where: { userId, normalizedQuantity: { gt: 0 }, expirationDate: { gte: now, lte: soon } }, include: { ingredient: true }, orderBy: { expirationDate: "asc" }, take: 4 }),
    db.inventoryItem.findMany({ where: { userId, minimumStock: { not: null }, normalizedQuantity: { gt: 0 } }, include: { ingredient: true }, take: 4 }),
    db.leftover.findMany({ where: { userId, consumed: false }, orderBy: { expirationDate: "asc" }, take: 4 }),
    db.cookingEvent.findMany({ where: { userId }, include: { recipe: true }, orderBy: { cookedAt: "desc" }, take: 3 }),
    getCompatibleRecipes(userId, { servings: 4, mode: "IN_STOCK" }),
    db.shoppingItem.count({ where: { userId, completed: false } }),
  ]);
  const actualLowStock = lowStock.filter((item) => item.minimumStock && Number(item.normalizedQuantity) <= Number(item.minimumStock)); const daily = recipes[0];
  return <><PageHeader eyebrow="Tu cocina hoy" title={`Hola, ${session?.user.name?.split(" ")[0] || "chef"}`} description="Tenés todo ordenado para decidir rápido y aprovechar mejor cada alimento." action={<Link href="/despensa?add=true"><Button variant="outline"><Plus className="size-4" />Agregar alimentos</Button></Link>} />
    <Card className="relative mb-6 overflow-hidden border-0 bg-primary text-primary-foreground"><div className="absolute -right-12 -top-16 size-52 rounded-full bg-white/10" /><CardContent className="relative grid gap-6 p-6 sm:p-8 md:grid-cols-[1fr_auto] md:items-center"><div><Badge className="mb-3 bg-white/15 text-white">Recomendación del día</Badge><h2 className="max-w-2xl text-2xl font-extrabold tracking-tight sm:text-3xl">{daily?.recipe.name ?? "Tu próxima comida empieza en la despensa"}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/80">{daily?.recipe.description ?? "Agregá algunos alimentos y te mostraremos recetas que podés cocinar sin comprar nada."}</p></div><Link href={daily ? `/recetas/${daily.recipe.slug}` : "/despensa?add=true"}><Button size="lg" className="bg-white text-primary hover:bg-white/90">{daily ? "Ver receta" : "Cargar alimentos"}<ArrowRight className="size-4" /></Button></Link></CardContent></Card>
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[[PackageOpen, inventoryCount, "productos disponibles", "/despensa"], [CalendarClock, expiring.length, "próximos a vencer", "/despensa?sort=expiration"], [ShoppingBasket, shoppingCount, "en la lista", "/compras"], [ChefHat, leftovers.length, "sobras guardadas", "/despensa"]].map(([Icon, value, label, href]) => { const ItemIcon = Icon as typeof PackageOpen; return <Link href={String(href)} key={String(label)}><Card className="h-full"><CardContent className="p-4 sm:p-5"><ItemIcon className="mb-4 size-5 text-primary" /><strong className="block text-2xl font-extrabold">{String(value)}</strong><span className="text-xs text-muted-foreground sm:text-sm">{String(label)}</span></CardContent></Card></Link>; })}</div>
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarClock className="size-5 text-amber-600" />Usá primero</CardTitle><CardDescription>Productos que vencen durante los próximos 7 días.</CardDescription></CardHeader><CardContent>{expiring.length ? <div className="space-y-3">{expiring.map((item) => <div className="flex items-center justify-between rounded-2xl bg-muted p-3" key={item.id}><div><p className="font-semibold capitalize">{item.ingredient?.canonicalName ?? item.customName}</p><p className="text-xs text-muted-foreground">{Number(item.quantity)} {item.unit}</p></div><Badge tone="amber">{formatDate(item.expirationDate)}</Badge></div>)}</div> : <Empty icon={Sparkles} text="No hay vencimientos cercanos. Bien ahí." />}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><CircleGauge className="size-5 text-primary" />Para tener en cuenta</CardTitle><CardDescription>Stock bajo, sobras y actividad reciente.</CardDescription></CardHeader><CardContent className="space-y-3">{actualLowStock.map((item) => <Link href="/compras" key={item.id} className="flex items-center justify-between rounded-2xl bg-muted p-3"><span className="font-semibold capitalize">Queda poco de {item.ingredient?.canonicalName ?? item.customName}</span><Badge tone="red">Stock bajo</Badge></Link>)}{leftovers.map((item) => <div key={item.id} className="flex items-center justify-between rounded-2xl bg-muted p-3"><span><strong className="block">{item.name}</strong><small className="text-muted-foreground">{item.portions} porciones · {item.location === "FRIDGE" ? "Heladera" : "Freezer"}</small></span><Badge tone="green">Sobra</Badge></div>)}{recent.map((event) => <Link href="/historial" key={event.id} className="flex items-center justify-between rounded-2xl bg-muted p-3"><span><strong className="block">{event.recipe.name}</strong><small className="text-muted-foreground">{formatDate(event.cookedAt)}</small></span><ArrowRight className="size-4 text-muted-foreground" /></Link>)}{!actualLowStock.length && !leftovers.length && !recent.length && <Empty icon={ChefHat} text="Cuando cocines, tu actividad aparecerá acá." />}</CardContent></Card></div>
  </>;
}
function Empty({ icon: Icon, text }: { icon: typeof Sparkles; text: string }) { return <div className="grid min-h-32 place-items-center rounded-2xl border border-dashed border-border p-6 text-center"><div><Icon className="mx-auto mb-2 size-7 text-muted-foreground" /><p className="text-sm text-muted-foreground">{text}</p></div></div>; }
