"use client";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { CalendarDays, Check, Edit3, PackageOpen, Plus, Search, Sparkles, Soup, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { acceptedUnits, categoryLabels, locationLabels } from "@/domain/catalog";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input, Label, Select, Textarea } from "@/components/ui/form-controls";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { formatDate } from "@/lib/utils";

type Item = { id: string; customName: string | null; quantity: string | number; unit: string; normalizedQuantity: string | number; location: string; expirationDate: string | null; opened: boolean; minimumStock: string | number | null; ingredient: { canonicalName: string; category: string } | null };
type Leftover = { id: string; name: string; portions: number; location: string; expirationDate: string | null; notes: string | null };
type Fields = { name: string; quantity: number; unit: (typeof acceptedUnits)[number]; location: "FRIDGE" | "FREEZER" | "PANTRY"; expirationDate: string; opened: boolean; minimumStock: number | null };
type Detected = { name: string; quantity: number; unit: Fields["unit"]; estimatedGrams?: number | null; estimatedMilliliters?: number | null; confidence: number; approximate: boolean; location?: Fields["location"] };
const defaults: Fields = { name: "", quantity: 1, unit: "unidad", location: "PANTRY", expirationDate: "", opened: false, minimumStock: null };

export function InventoryScreen({ initialItems, leftovers, autoOpen }: { initialItems: Item[]; leftovers: Leftover[]; autoOpen: boolean }) {
  const [items, setItems] = useState(initialItems); const [manualOpen, setManualOpen] = useState(autoOpen); const [quickOpen, setQuickOpen] = useState(false); const [editing, setEditing] = useState<Item | null>(null);
  const [search, setSearch] = useState(""); const [location, setLocation] = useState(""); const [category, setCategory] = useState(""); const [sort, setSort] = useState("expiration");
  const [quickText, setQuickText] = useState("Tengo 2 kilos de papa, 6 huevos, un pollo, medio kilo de cebolla y una taza de arroz."); const [detected, setDetected] = useState<Detected[]>([]); const [interpreting, setInterpreting] = useState(false);
  const { register, handleSubmit, reset, formState: { isSubmitting } } = useForm<Fields>({ defaultValues: defaults });
  const filtered = useMemo(() => items.filter((item) => { const name = (item.ingredient?.canonicalName ?? item.customName ?? "").toLocaleLowerCase(); return name.includes(search.toLocaleLowerCase()) && (!location || item.location === location) && (!category || item.ingredient?.category === category); }).sort((a, b) => sort === "name" ? (a.ingredient?.canonicalName ?? a.customName ?? "").localeCompare(b.ingredient?.canonicalName ?? b.customName ?? "") : sort === "quantity" ? Number(a.normalizedQuantity) - Number(b.normalizedQuantity) : new Date(a.expirationDate ?? "2999-01-01").getTime() - new Date(b.expirationDate ?? "2999-01-01").getTime()), [items, search, location, category, sort]);
  function openEdit(item: Item) { setEditing(item); reset({ name: item.ingredient?.canonicalName ?? item.customName ?? "", quantity: Number(item.quantity), unit: item.unit as Fields["unit"], location: item.location as Fields["location"], expirationDate: item.expirationDate?.slice(0, 10) ?? "", opened: item.opened, minimumStock: item.minimumStock == null ? null : Number(item.minimumStock) }); setManualOpen(true); }
  function openNew() { setEditing(null); reset(defaults); setManualOpen(true); }
  const save = handleSubmit(async (values) => { const response = await fetch(editing ? `/api/inventory/${editing.id}` : "/api/inventory", { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...values, expirationDate: values.expirationDate || null, minimumStock: values.minimumStock || null }) }); const data = await response.json(); if (!response.ok) return toast.error(data.error); if (editing) setItems((current) => current.map((item) => item.id === editing.id ? data.item : item)); else setItems((current) => [data.item, ...current]); toast.success(editing ? "Producto actualizado" : "Producto agregado"); setManualOpen(false); });
  async function remove(item: Item) { if (!confirm(`¿Eliminar ${item.ingredient?.canonicalName ?? item.customName} de tu despensa?`)) return; const response = await fetch(`/api/inventory/${item.id}`, { method: "DELETE" }); if (response.ok) { setItems((current) => current.filter((value) => value.id !== item.id)); toast.success("Producto eliminado"); } else toast.error("No se pudo eliminar"); }
  async function markEmpty(item: Item) { const response = await fetch(`/api/inventory/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ quantity: 0 }) }); if (response.ok) { const data = await response.json(); setItems((current) => current.map((value) => value.id === item.id ? data.item : value)); await fetch("/api/shopping", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: item.ingredient?.canonicalName ?? item.customName, quantity: 1, unit: item.unit, priority: "NORMAL", source: "OUT_OF_STOCK" }) }); toast.success("Marcado como agotado y agregado a compras"); } }
  async function interpret() { setInterpreting(true); const response = await fetch("/api/interpret", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ text: quickText }) }); const data = await response.json(); setInterpreting(false); if (!response.ok) return toast.error(data.error); setDetected(data.items.map((item: Detected) => ({ ...item, location: "PANTRY" }))); if (!data.items.length) toast.error("No detectamos productos del catálogo. Probá separarlos con comas."); }
  async function confirmDetected() { const response = await fetch("/api/inventory", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ items: detected.map((item) => ({ name: item.name, quantity: Number(item.quantity), unit: item.unit, location: item.location ?? "PANTRY", opened: false, expirationDate: null })) }) }); const data = await response.json(); if (!response.ok) return toast.error(data.error); setItems((current) => [...data.items, ...current]); setQuickOpen(false); setDetected([]); toast.success(`${data.items.length} productos agregados`); }
  return <><PageHeader eyebrow="Inventario" title="Mi despensa" description="Todo lo que tenés, ordenado por ubicación y vencimiento." action={<div className="flex gap-2"><Button variant="outline" onClick={() => setQuickOpen(true)}><Sparkles className="size-4" />Carga rápida</Button><Button onClick={openNew}><Plus className="size-4" />Agregar</Button></div>} />
    {leftovers.length > 0 && <section className="mb-6"><h2 className="mb-3 flex items-center gap-2 text-lg font-extrabold"><Soup className="size-5 text-primary" />Comidas preparadas</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{leftovers.map((item) => <Card key={item.id} className="border-primary/20 bg-primary/5"><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-extrabold">{item.name}</p><p className="mt-1 text-sm text-muted-foreground">{item.portions} porciones · {locationLabels[item.location]}</p></div><Badge tone="green">Sobra</Badge></div>{item.expirationDate && <p className="mt-3 text-xs text-muted-foreground">Consumir antes del {formatDate(item.expirationDate)}</p>}</CardContent></Card>)}</div></section>}
    <Card className="mb-5"><CardContent className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-5"><div className="relative sm:col-span-2"><Search className="absolute left-3 top-3 size-5 text-muted-foreground" /><Input className="pl-10" placeholder="Buscar alimentos" value={search} onChange={(event) => setSearch(event.target.value)} /></div><Select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Todas las categorías</option>{Object.entries(categoryLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</Select><Select value={location} onChange={(event) => setLocation(event.target.value)}><option value="">Todas las ubicaciones</option>{Object.entries(locationLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</Select><Select value={sort} onChange={(event) => setSort(event.target.value)}><option value="expiration">Vencimiento</option><option value="name">Nombre</option><option value="quantity">Cantidad</option></Select></CardContent></Card>
    {filtered.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => { const empty = Number(item.normalizedQuantity) <= 0; return <Card key={item.id} className={empty ? "opacity-60" : ""}><CardContent className="p-5"><div className="mb-4 flex items-start justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-secondary"><PackageOpen className="size-5 text-secondary-foreground" /></span><div className="flex gap-1"><Button variant="ghost" size="sm" aria-label="Editar" onClick={() => openEdit(item)}><Edit3 className="size-4" /></Button><Button variant="ghost" size="sm" aria-label="Eliminar" onClick={() => remove(item)}><Trash2 className="size-4 text-destructive" /></Button></div></div><h2 className="text-lg font-bold capitalize">{item.ingredient?.canonicalName ?? item.customName}</h2><p className="mt-1 text-2xl font-extrabold">{Number(item.quantity).toLocaleString("es-AR")} <span className="text-sm font-semibold text-muted-foreground">{item.unit}</span></p><div className="mt-4 flex flex-wrap gap-2"><Badge tone={empty ? "red" : "green"}>{empty ? "Agotado" : locationLabels[item.location]}</Badge>{item.opened && <Badge tone="amber">Abierto</Badge>}{item.expirationDate && <Badge tone="amber"><CalendarDays className="mr-1 size-3" />{formatDate(item.expirationDate)}</Badge>}</div>{!empty && <Button className="mt-4 w-full" variant="outline" size="sm" onClick={() => markEmpty(item)}><Check className="size-4" />Marcar agotado</Button>}</CardContent></Card>; })}</div> : <Card><CardContent className="grid min-h-72 place-items-center text-center"><div><PackageOpen className="mx-auto mb-4 size-12 text-muted-foreground" /><h2 className="text-xl font-bold">Tu despensa está lista para llenarse</h2><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">Agregá alimentos manualmente o pegá una frase y revisá lo que detectamos.</p><Button className="mt-5" onClick={() => setQuickOpen(true)}>Probar carga rápida</Button></div></CardContent></Card>}
    <Modal open={manualOpen} onClose={() => setManualOpen(false)} title={editing ? "Editar producto" : "Agregar alimento"} description="Las equivalencias caseras se guardan como aproximadas."><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Producto</Label><Input placeholder="Ej. papa" {...register("name", { required: true })} /></div><div><Label>Cantidad</Label><Input type="number" step="any" min="0" {...register("quantity", { valueAsNumber: true, required: true })} /></div><div><Label>Unidad</Label><Select {...register("unit")}>{acceptedUnits.map((unit) => <option key={unit}>{unit}</option>)}</Select></div><div><Label>Ubicación</Label><Select {...register("location")}><option value="FRIDGE">Heladera</option><option value="FREEZER">Freezer</option><option value="PANTRY">Alacena</option></Select></div><div><Label>Vencimiento</Label><Input type="date" {...register("expirationDate")} /></div><div><Label>Stock mínimo</Label><Input type="number" step="any" min="0" placeholder="Opcional" {...register("minimumStock", { setValueAs: (value) => value === "" ? null : Number(value) })} /></div><label className="flex items-center gap-2 self-end pb-3 text-sm font-semibold"><input type="checkbox" {...register("opened")} /> Producto abierto</label><div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="ghost" onClick={() => setManualOpen(false)}>Cancelar</Button><Button disabled={isSubmitting}>{isSubmitting ? "Guardando…" : "Guardar producto"}</Button></div></form></Modal>
    <Modal open={quickOpen} onClose={() => setQuickOpen(false)} title="Carga rápida por texto" description="Interpretamos la frase, vos revisás y recién después guardamos."><Textarea value={quickText} onChange={(event) => setQuickText(event.target.value)} /><Button className="mt-3 w-full" onClick={interpret} disabled={interpreting}>{interpreting ? "Interpretando…" : "Detectar productos"}</Button>{detected.length > 0 && <div className="mt-5 space-y-3"><p className="text-sm font-bold">Productos detectados</p>{detected.map((item, index) => <div className="grid gap-2 rounded-2xl bg-muted p-3 sm:grid-cols-[1fr_7rem_9rem]" key={`${item.name}-${index}`}><Input value={item.name} onChange={(event) => setDetected((values) => values.map((value, i) => i === index ? { ...value, name: event.target.value } : value))} /><Input type="number" step="any" value={item.quantity} onChange={(event) => setDetected((values) => values.map((value, i) => i === index ? { ...value, quantity: Number(event.target.value) } : value))} /><Select value={item.unit} onChange={(event) => setDetected((values) => values.map((value, i) => i === index ? { ...value, unit: event.target.value as Fields["unit"] } : value))}>{acceptedUnits.map((unit) => <option key={unit}>{unit}</option>)}</Select>{item.approximate && <p className="text-xs text-amber-700 sm:col-span-3">≈ {item.estimatedGrams ? `${item.estimatedGrams} g` : item.estimatedMilliliters ? `${item.estimatedMilliliters} ml` : "conversión aproximada"}</p>}</div>)}<div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setDetected([])}>Corregir frase</Button><Button onClick={confirmDetected}><Check className="size-4" />Confirmar y agregar</Button></div></div>}</Modal>
  </>;
}
