"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, ChefHat, Clock3, MinusCircle, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input, Label, Select, Textarea } from "@/components/ui/form-controls";
import { Modal } from "@/components/ui/modal";

type Batch = { id: string; normalizedQuantity: string | number; quantity: string | number; unit: string };
type StockLine = { ingredient: { id: string; canonicalName: string }; required: { normalizedQuantity: string | number; unit: string; quantity: string | number; householdMeasure: string | null; substitutions: string[]; optional: boolean }; needed: number; stock: number; missing: number; batches: Batch[] };
type Data = { recipe: { id: string; name: string; description: string; servings: number; prepTime: number; cookTime: number; difficulty: string; instructions: string[]; tags: string[]; estimatedCalories: number | null; estimatedProtein: string | number | null; ingredients: Array<{ id: string; quantity: string | number; unit: string; normalizedQuantity: string | number; householdMeasure: string | null; optional: boolean; substitutions: string[]; ingredient: { id: string; canonicalName: string } }> }; requestedServings: number; compatibility: { score: number; canCook: boolean; available: StockLine[]; missing: StockLine[] } };
type Usage = { inventoryItemId: string; ingredientId: string; name: string; plannedQuantity: number; actualQuantity: number; stock: number };
export function RecipeDetail({ data }: { data: Data }) {
  const router = useRouter(); const { recipe, compatibility, requestedServings } = data; const factor = requestedServings / recipe.servings; const [open, setOpen] = useState(false); const [submitting, setSubmitting] = useState(false); const [leftover, setLeftover] = useState(false); const [portions, setPortions] = useState(1); const [leftoverLocation, setLeftoverLocation] = useState("FRIDGE"); const [expiration, setExpiration] = useState(""); const [notes, setNotes] = useState("");
  const initialUsages = useMemo(() => compatibility.available.flatMap((line) => { let remaining = line.needed; return line.batches.flatMap((batch) => { if (remaining <= 0) return []; const used = Math.min(remaining, Number(batch.normalizedQuantity)); remaining -= used; return [{ inventoryItemId: batch.id, ingredientId: line.ingredient.id, name: line.ingredient.canonicalName, plannedQuantity: used, actualQuantity: used, stock: Number(batch.normalizedQuantity) }]; }); }), [compatibility.available]);
  const [usages, setUsages] = useState<Usage[]>(initialUsages);
  async function confirmCooked() { setSubmitting(true); const response = await fetch("/api/cook", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ recipeId: recipe.id, servings: requestedServings, usages, notes, leftover: leftover ? { portions, location: leftoverLocation, expirationDate: expiration || null } : null }) }); const result = await response.json(); setSubmitting(false); if (!response.ok) return toast.error(result.error); toast.success("¡Comida registrada y stock actualizado!"); router.push("/historial"); router.refresh(); }
  async function addMissingToShopping() { for (const line of compatibility.missing) await fetch("/api/shopping", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: line.ingredient.canonicalName, quantity: Number(line.required.quantity) * factor, unit: line.required.unit, priority: "NORMAL", source: "RECIPE" }) }); toast.success("Ingredientes faltantes agregados a compras"); }
  return <><Button variant="ghost" className="mb-4 -ml-3" onClick={() => router.back()}><ArrowLeft className="size-4" />Volver</Button><header className="mb-7"><div className="mb-3 flex flex-wrap gap-2">{recipe.tags.map((tag) => <Badge key={tag}>{tag}</Badge>)}<Badge tone={compatibility.canCook ? "green" : "amber"}>{compatibility.score}% compatible</Badge></div><h1 className="max-w-4xl text-3xl font-extrabold tracking-[-.045em] sm:text-5xl">{recipe.name}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted-foreground">{recipe.description}</p><div className="mt-5 flex flex-wrap gap-5 text-sm font-semibold"><span className="flex items-center gap-2"><Clock3 className="size-4 text-primary" />{recipe.prepTime + recipe.cookTime} minutos</span><span className="flex items-center gap-2"><UsersRound className="size-4 text-primary" />{requestedServings} porciones</span><span className="flex items-center gap-2"><ChefHat className="size-4 text-primary" />{recipe.difficulty === "EASY" ? "Fácil" : recipe.difficulty === "MEDIUM" ? "Media" : "Difícil"}</span></div></header>
    <div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><Card><CardHeader><CardTitle>Ingredientes</CardTitle></CardHeader><CardContent className="space-y-3">{recipe.ingredients.map((item) => { const missing = compatibility.missing.find((line) => line.ingredient.id === item.ingredient.id); return <div key={item.id} className="flex items-start gap-3 rounded-2xl bg-muted p-3"><span className={`mt-1 grid size-5 shrink-0 place-items-center rounded-full ${missing ? "bg-amber-100 text-amber-700" : "bg-primary/15 text-primary"}`}>{missing ? <MinusCircle className="size-4" /> : <CheckCircle2 className="size-4" />}</span><div><p className="font-semibold capitalize">{(Number(item.quantity) * factor).toLocaleString("es-AR", { maximumFractionDigits: 2 })} {item.unit} de {item.ingredient.canonicalName}</p>{item.householdMeasure && factor === 1 && <p className="text-xs text-muted-foreground">≈ {item.householdMeasure}</p>}{item.substitutions.length > 0 && <p className="mt-1 text-xs text-muted-foreground">Podés reemplazar por: {item.substitutions.join(", ")}</p>}</div></div>; })}{compatibility.missing.length > 0 && <div className="rounded-2xl bg-amber-50 p-3 text-sm text-amber-800"><p>Te falta: {compatibility.missing.map((item) => item.ingredient.canonicalName).join(", ")}.</p><Button className="mt-3" size="sm" variant="outline" onClick={addMissingToShopping}>Agregar faltantes a compras</Button></div>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Preparación</CardTitle></CardHeader><CardContent><ol className="space-y-5">{recipe.instructions.map((step, index) => <li key={index} className="flex gap-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-primary text-sm font-extrabold text-primary-foreground">{index + 1}</span><p className="pt-1 text-sm leading-6 sm:text-base">{step}</p></li>)}</ol>{recipe.estimatedCalories && <div className="mt-7 rounded-2xl border border-border bg-background p-4 text-sm"><strong>Nutrición estimada para {requestedServings} porciones</strong><p className="mt-1 text-muted-foreground">≈ {Math.round(recipe.estimatedCalories * factor)} kcal · ≈ {(Number(recipe.estimatedProtein) * factor).toLocaleString("es-AR", { maximumFractionDigits: 1 })} g de proteína. No constituye indicación médica.</p></div>}</CardContent></Card></div>
    <div className="sticky bottom-20 z-20 mt-6 rounded-2xl border border-border bg-card/95 p-3 shadow-lg backdrop-blur lg:bottom-4"><Button size="lg" className="w-full" disabled={!compatibility.canCook} onClick={() => setOpen(true)}>{compatibility.canCook ? "Cociné esta receta" : "Faltan ingredientes para cocinar"}</Button></div>
    <Modal open={open} onClose={() => setOpen(false)} title="Confirmar lo que usaste" description="El stock se descontará únicamente cuando confirmes."><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="pb-2">Ingrediente</th><th>Stock actual</th><th>Se usará</th><th>Quedará</th></tr></thead><tbody>{usages.map((usage, index) => <tr key={usage.inventoryItemId} className="border-t border-border"><td className="py-3 font-semibold capitalize">{usage.name}</td><td>{usage.stock.toLocaleString("es-AR")}</td><td><Input className="h-9 w-24" type="number" step="any" min="0.001" max={usage.stock} value={usage.actualQuantity} onChange={(event) => setUsages((current) => current.map((item, i) => i === index ? { ...item, actualQuantity: Number(event.target.value) } : item))} /></td><td>{Math.max(0, usage.stock - usage.actualQuantity).toLocaleString("es-AR")}</td></tr>)}</tbody></table></div><div className="mt-5 border-t border-border pt-5"><label className="flex items-center gap-2 font-semibold"><input type="checkbox" checked={leftover} onChange={(event) => setLeftover(event.target.checked)} />¿Quedaron porciones?</label>{leftover && <div className="mt-4 grid gap-3 sm:grid-cols-3"><div><Label>Porciones</Label><Input type="number" min="1" value={portions} onChange={(event) => setPortions(Number(event.target.value))} /></div><div><Label>Ubicación</Label><Select value={leftoverLocation} onChange={(event) => setLeftoverLocation(event.target.value)}><option value="FRIDGE">Heladera</option><option value="FREEZER">Freezer</option></Select></div><div><Label>Consumir antes de</Label><Input type="date" value={expiration} onChange={(event) => setExpiration(event.target.value)} /></div></div>}<div className="mt-4"><Label>Notas opcionales</Label><Textarea className="min-h-20" value={notes} onChange={(event) => setNotes(event.target.value)} /></div></div><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setOpen(false)}>Cancelar</Button><Button onClick={confirmCooked} disabled={submitting || usages.some((item) => item.actualQuantity <= 0 || item.actualQuantity > item.stock)}>{submitting ? "Actualizando stock…" : "Confirmar y descontar"}</Button></div></Modal>
  </>;
}
