"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ChefHat, Clock3, CookingPot, SlidersHorizontal, Sparkles, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input, Label, Select } from "@/components/ui/form-controls";

type Result = { recipe: { id: string; slug: string; name: string; description: string; servings: number; prepTime: number; cookTime: number; difficulty: string; tags: string[]; ingredients: Array<{ ingredient: { canonicalName: string } }> }; compatibility: { score: number; canCook: boolean; available: Array<{ ingredient: { canonicalName: string } }>; missing: Array<{ ingredient: { canonicalName: string }; missing: number }>; expiringIngredients: Array<{ canonicalName: string }> } };
export function RecipeFinder({ initialResults, defaultServings }: { initialResults: Result[]; defaultServings: number }) {
  const [results, setResults] = useState(initialResults); const [loading, setLoading] = useState(false); const [servings, setServings] = useState(defaultServings); const [maxTime, setMaxTime] = useState(60); const [difficulty, setDifficulty] = useState(""); const [mode, setMode] = useState("IN_STOCK"); const [include, setInclude] = useState(""); const [exclude, setExclude] = useState(""); const [expiring, setExpiring] = useState(false);
  async function search() { setLoading(true); const params = new URLSearchParams({ servings: String(servings), maxTime: String(maxTime), mode, ...(difficulty ? { difficulty } : {}), ...(include ? { include } : {}), ...(exclude ? { exclude } : {}), expiringFirst: String(expiring) }); const response = await fetch(`/api/recipes?${params}`); const data = await response.json(); setLoading(false); if (!response.ok) return toast.error(data.error); setResults(data.results); }
  const now = results.filter((item) => item.compatibility.canCook); const almost = results.filter((item) => !item.compatibility.canCook && item.compatibility.missing.length <= 2); const expiringRecipes = expiring ? results.filter((item) => item.compatibility.expiringIngredients.length > 0) : [];
  return <><PageHeader eyebrow="Sugerencias" title="¿Qué cocinamos hoy?" description="Elegí tus prioridades. Las recetas se comparan con el stock real de tu despensa." />
    <Card className="mb-8"><CardHeader><CardTitle className="flex items-center gap-2"><SlidersHorizontal className="size-5 text-primary" />Ajustá tu comida</CardTitle><CardDescription>Podés cambiar los filtros todas las veces que quieras.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><Label>Personas</Label><Input type="number" min="1" max="20" value={servings} onChange={(event) => setServings(Number(event.target.value))} /></div><div><Label>Tiempo máximo</Label><Select value={maxTime} onChange={(event) => setMaxTime(Number(event.target.value))}><option value="30">30 minutos</option><option value="45">45 minutos</option><option value="60">1 hora</option><option value="120">2 horas</option></Select></div><div><Label>Dificultad</Label><Select value={difficulty} onChange={(event) => setDifficulty(event.target.value)}><option value="">Cualquiera</option><option value="EASY">Fácil</option><option value="MEDIUM">Media</option><option value="HARD">Difícil</option></Select></div><div><Label>Modo</Label><Select value={mode} onChange={(event) => setMode(event.target.value)}><option value="IN_STOCK">Con lo que tengo</option><option value="ONE_MISSING">Puede faltar algo</option><option value="FIT">Fit</option><option value="HIGH_PROTEIN">Alto en proteínas</option><option value="BUDGET">Económico</option><option value="QUICK">Rápido</option><option value="FREEZER">Para freezer</option></Select></div><div className="lg:col-span-2"><Label>Quiero usar</Label><Input placeholder="pollo, papa" value={include} onChange={(event) => setInclude(event.target.value)} /></div><div className="lg:col-span-2"><Label>No quiero usar</Label><Input placeholder="cebolla" value={exclude} onChange={(event) => setExclude(event.target.value)} /></div><label className="flex items-center gap-2 text-sm font-semibold lg:col-span-2"><input type="checkbox" checked={expiring} onChange={(event) => setExpiring(event.target.checked)} />Priorizar lo que está por vencer</label><Button className="lg:col-span-2" onClick={search} disabled={loading}>{loading ? "Buscando…" : "Buscar recetas"}<Sparkles className="size-4" /></Button></CardContent></Card>
    <RecipeGroup title="Podés cocinar ahora" description="Tenés todos los ingredientes necesarios." results={now} servings={servings} icon={CookingPot} empty="No encontramos una receta completa con esos filtros." />
    <RecipeGroup title="Te falta muy poco" description="Falta uno o dos ingredientes." results={almost} servings={servings} icon={ChefHat} empty="Las recetas incompletas aparecerán acá." />
    {expiring && <RecipeGroup title="Aprovechá antes de que venza" description="Usan alimentos con vencimiento cercano." results={expiringRecipes} servings={servings} icon={Clock3} empty="No hay coincidencias con vencimientos cercanos." />}
  </>;
}
function RecipeGroup({ title, description, results, servings, icon: Icon, empty }: { title: string; description: string; results: Result[]; servings: number; icon: typeof CookingPot; empty: string }) { return <section className="mb-9"><div className="mb-4"><h2 className="flex items-center gap-2 text-xl font-extrabold"><Icon className="size-5 text-primary" />{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{results.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{results.map(({ recipe, compatibility }) => <Card key={recipe.id} className="group flex h-full flex-col overflow-hidden"><div className="h-2 bg-gradient-to-r from-primary to-amber-400" /><CardContent className="flex flex-1 flex-col p-5"><div className="mb-3 flex items-start justify-between gap-3"><Badge tone={compatibility.canCook ? "green" : "amber"}>{compatibility.score}% compatible</Badge><span className="flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="size-3" />{recipe.prepTime + recipe.cookTime} min</span></div><h3 className="text-xl font-extrabold tracking-tight">{recipe.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{recipe.description}</p><div className="mt-3 flex flex-wrap gap-1.5">{recipe.tags.slice(0, 3).map((tag) => <Badge key={tag}>{tag}</Badge>)}</div><div className="mt-auto pt-5"><div className="mb-4 flex items-center gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1"><UsersRound className="size-4" />{servings} porciones</span><span>{recipe.difficulty === "EASY" ? "Fácil" : recipe.difficulty === "MEDIUM" ? "Media" : "Difícil"}</span></div>{compatibility.missing.length > 0 && <p className="mb-3 text-xs text-amber-700">Falta: {compatibility.missing.map((item) => item.ingredient.canonicalName).join(", ")}</p>}<Link href={`/recetas/${recipe.slug}?servings=${servings}`}><Button className="w-full" variant={compatibility.canCook ? "default" : "outline"}>Ver receta<ArrowRight className="size-4 transition group-hover:translate-x-1" /></Button></Link></div></CardContent></Card>)}</div> : <Card className="border-dashed shadow-none"><CardContent className="py-9 text-center text-sm text-muted-foreground">{empty}</CardContent></Card>}</section>; }
